export const CHANGE_MODULE_FORM = 'CHANGE_MODULE_FORM';
export const START_MODULE_TEST = 'START_MODULE_TEST';
export const TEST_MODULE_CHILD_ACTION = 'TEST_MODULE_CHILD_ACTION';
export const DISPATCH_MODULE_ACTION = 'DISPATCH_MODULE_ACTION';
export const CHANGE_ACTION_FORM = 'CHANGE_ACTION_FORM';
